# gere o codigo para enviar um post para https://server.growatt.com/indexbC/getTotalData com o seguint body 'plantId': '181869'
# e retorne o json da respost usando sintaxe de rest client
# Dica: use a extensão REST Client do VSCode

POST https://server.growatt.com/indexbC/getTotalData
Content-Type: application/json

{
    "plantId": "181869"
}



obj
: 
{eRadiant: "0", pr: "0", mTotal: "125350.9", accountName: "IFMG", faultNum: "0", mToday: "70.1",…}
accountName
: 
"IFMG"
co2
: 
"62309.4"
coa
: 
"62309.4"
deviceNum
: 
"1"
eMonth
: 
"2458.4"
eRadiant
: 
"0"
eToday
: 
"87.1"
eTotal
: 
"155773.5"
etodayRadiation
: 
"0"
faultNum
: 
"0"
followUpNum
: 
"0"
gridDate
: 
"2019-08-10"
isEnv
: 
"false"
lostNum
: 
"0"
mMonth
: 
"1978.3"
mToday
: 
"70.1"
mTotal
: 
"125350.9"
mUnitText
: 
"¥"
nominalPower
: 
"25000"
omTotal
: 
"0"
onlineNum
: 
"1"
pac
: 
"726.4"
plantId
: 
"181869"
plantImgName
: 
"181869_1images1569607464904.jpg"
pr
: 
"0"
processeingNum
: 
"0"
runDay
: 
"1996"
solvedNum
: 
"0"
tree
: 
"8568"
waitNum
: 
"0"
result
: 
1